### ISSUE TITLE
Running BigBacter

### ISSUE THREAD

**Issue by whottel** [DOH-JDJ0303/bigbacter-nf#4]
### Description of the bug

Run command immediately fails when trying to follow “Running BigBacter” instructions at “Preparing the PopPUNK Database”.

### Command used and terminal output

```console
nextflow run DOH-JDJ0303/bigbacter-nf     -r main     -profile singularity,all_dbs     -entry PREPARE_DB     --db $PWD/db

N E X T F L O W  ~  version 22.10.3
Pulling DOH-JDJ0303/bigbacter-nf ...
Failure updating tracking ref refs/remotes/origin/main: Cannot read file /Users/hottel/.nextflow/assets/DOH-JDJ0303/bigbacter-nf/.git/refs/tags/βeta
```

### Relevant files

[nextflow.log](https://github.com/DOH-JDJ0303/bigbacter-nf/files/14594183/nextflow.log)

### System information

Nextflow version 22.10.3
Running on HPC, local executor

**Comment by DOH-JDJ0303** [comment]
Hi @whottel. This is a new one to me. Below are some things I would test first:

1. Update Nextflow. It looks like you are using an old version of Nextflow. I would recommend updating to the most recent version: [Version 23.10.1](https://github.com/nextflow-io/nextflow/releases/tag/v23.10.1)
2. Delete `/Users/hottel/.nextflow/assets/DOH-JDJ0303/bigbacter-nf/` and try again.

If neither of those work, my next guess would be that your system doesn't like 'β' symbol in the tag name. If this the case, I can release a new version without that symbol.

**Comment by whottel** [comment]
Hello,
I was able to update to Nextflow 23.10.1 and deleted that directory. I still am getting the same error message. I am also guessing it is due to the 'β' character in the tag name.

**Comment by DOH-JDJ0303** [comment]
Ok, I made a new [release](https://github.com/DOH-JDJ0303/bigbacter-nf/releases/tag/beta) with a new name that should hopefully fix this issue. Let me know if that doesn't work and I will keep brainstorming solutions.

**Comment by whottel** [comment]
Thanks for making that new release unfortunately I am still getting the same error.
As a workaround I was able to fork the main repository to my organizations github page. This does not have the βeta tag, and I was able to pull from there successfully. 
Unfortunately I was not able to run the command to download all PopPUNK databases. It seems I kept running into connection issues.
I was however, able to pull the Legionella pneumophila database individually following the instructions in the wiki page. 
From here I am still having trouble running BigBacter. I am getting a not valid path value error for my .fasta files, see attached log:
[log.txt.txt](https://github.com/DOH-JDJ0303/bigbacter-nf/files/14618891/log.txt.txt)

I am attempting to run from a directory that contains the paried .fastq.gz, .fasta files, samplesheet.csv, as well as the results and db subfolders. I also tried to fill in the samplesheet.csv similar to what is shown on the wiki page:
[samplesheet.csv](https://github.com/DOH-JDJ0303/bigbacter-nf/files/14618892/samplesheet.csv)


I have also tried including the absolute path of the .fasta files in the samplesheet but continue to get the same error.

**Comment by DOH-JDJ0303** [comment]
Hi @whottel. I am glad that you were able to get it to work using a fork but this is not ideal. I wonder if you would have luck deleting `/Users/hottel/.nextflow/assets/DOH-JDJ0303/bigbacter-nf/` again and then trying to run 'nextflow pull https://github.com/DOH-JDJ0303/bigbacter-nf'. This should hopefully get rid of any funkiness that may have occurred from the previous tag name. 

Regarding the database download issue, it looks like you forked the repo just before I made change to address this issue. If the approach above does not work, then I would recommend re-forking the repo if you want to download all available databases. The update limits the downloads to one file at a time when running `-profile all_dbs`. This was something I overlooked because my testing was peformed using AWS Batch. It should work anywhere now.

Regarding the `not valid path` error, Nextflow requires absolute paths to files in the samplesheet (sorry this was unclear in the example). That said, your samplesheet containing absolute paths should have worked. Are you able to share this file so I can look for any issues? It is also probably worth double checking to make sure the paths are correct.

Thanks for working through all these bugs with me!

**Comment by whottel** [comment]
Apologies, I was out of the lab all last week. I should have time this week to look more into this. 
Thanks,
Wes

**Comment by whottel** [comment]
For deleting the bigbacter-ngf and then re-pulling I continue to get the same error. 
I merged my forked repository with the most recent commits as of 3/26. 
I ran this command `nextflow run SHL-Bioinfo/bigbacter-nf -r main -profile singularity,all_dbs -entry PREPARE_DB --db $PWD/db`
However, I was again getting connection errors see 
[nextflow_log_db_download.log](https://github.com/DOH-JDJ0303/bigbacter-nf/files/14764550/nextflow_log_db_download.log)
In positive news I was able to get the pipeline to run after adding the absolute paths to samplesheet.csv, I must have had a typo when I tried this previously. However, the gubbins process did fail please find error log:
[gubbins_command_error.txt](https://github.com/DOH-JDJ0303/bigbacter-nf/files/14764753/gubbins_command_error.txt)

**Comment by whottel** [comment]
I was able to download all the databases using the same command as mentioned above. I must have been having bad luck with connectivity issues on my prior attempts. 

As for the command, I am running with `-profile singularity`
Full command: `/Shared/SHL-BUG/software/nextflow/nextflow run SHL-Bioinfo/bigbacter-nf -r main -profile singularity --input $PWD/samplesheet.csv --outdir $PWD/results --db $PWD/db`

Unfortunately we are limited to using singularity on our system.

**Comment by DOH-JDJ0303** [comment]
Hi @whottel. Glad to hear that the databases are downloading now. I did some more digging on the Gubbins issue and it turns out this is an active bug with the tool [Gubbins Issue 396](https://github.com/nickjcroucher/gubbins/issues/396). I updated Gubbins to v3.3.4, which is supposed to fix this issue but there appears to be an issue with the docker/singularity containers [Bioconda pull 46713](https://github.com/bioconda/bioconda-recipes/pull/46713). Unfortunately, I do not have an immediate fix but I anticipate this is something the Bioconda/Gubbins developers will want to get fixed quick.

All that said, your BigBacter run should still complete even when Gubbins fails. I set it up this way because Gubbins has a lot of issues. Let me know if that is not the case.

I am going to close this and open a [new issue](https://github.com/DOH-JDJ0303/bigbacter-nf/issues/7) specific the Gubbins problem. I will link you and this comment in that new issue.

**Comment by DOH-JDJ0303** [comment]
@whottel, I think we have a solution to the Gubbins issue (see [issue 7](https://github.com/DOH-JDJ0303/bigbacter-nf/issues/7)). Sounds like the error is due to a recent update to Nextflow that changed Singularity behavior. Running `export NXF_SINGULARITY_HOME_MOUNT=true` prior BigBacter should hopefully solve the issue.

**Comment by whottel** [comment]
That worked!
Thanks some much troubleshooting these issues.

**Comment by DOH-JDJ0303** [comment]
Thank you, @whottel!
